### ISSUE TITLE
Standard Data Format

### ISSUE THREAD

**Issue by antani** [anfederico/Clairvoyant#10]
I am using standard Yahoo downloads in the format

    Date,Open,High,Low,Close,Volume,Close
    2015-01-01,312.45,315.0,310.7,314.0,6138488,314.0

When I run sample program (as per README) I get the following error -

    Traceback (most recent call last):
    File "clairvoyance.py", line 35, in <module>
    backtest.runModel(data)
    File "/Users/8288/source_code/finance/venv/lib/python2.7/site-packages/clairvoyant/Backtest.py", line 75, in runModel
    trainStart = DateIndex(data, stock, self.trainStart, False)
    File "/Users/8288/source_code/finance/venv/lib/python2.7/site-packages/clairvoyant/Backtest.py", line 16, in DateIndex
    lowbound = data["Date"][0]
    File "/Users/8288/source_code/finance/venv/lib/python2.7/site-packages/pandas/core/series.py", line 603, in __getitem__
    result = self.index.get_value(self, key)
    File "/Users/8288/source_code/finance/venv/lib/python2.7/site-packages/pandas/indexes/base.py", line 2175, in get_value
    return tslib.get_value_box(s, key)
    File "pandas/tslib.pyx", line 946, in pandas.tslib.get_value_box (pandas/tslib.c:19053)
    File "pandas/tslib.pyx", line 962, in pandas.tslib.get_value_box (pandas/tslib.c:18770)
    IndexError: index out of bounds

**Comment by anfederico** [comment]
Can you show me the full program you're trying to run? It will help me better understand what's going wrong.

**Comment by antani** [comment]
https://gist.github.com/antani/779d4dc8175efcfa427723f6524f0de8

**Comment by anfederico** [comment]
Here's your problem:
variables  = []

You need to tell the program which variables to model and which to ignore. For example, if you want to model the Open, Close, High, Low, and Volume of your data, you need to include the following.

variables = ["Open", "Close", "High", "Low", "Volume"]

**Comment by antani** [comment]
Works fine.
