### ISSUE TITLE
Does trainStart and trainEnd not support date formats anymore?

### ISSUE THREAD

**Issue by oppsig** [anfederico/Clairvoyant#21]
So basicly im downloading yahoo data and then convert the date format because I've seen in previously issues in this repo that you don't support yyyy-mm-dd?
So i convert from yyyy-mm-dd to mm-dd-yyyy.

Then i assign variables in the same date format.
I see from your example in readme that you are using integers here instead?
So is date not supported anymore?
As you can see in the traceback at the bottom dates don't work for me.
```
variables = ["Open", "Close", "High", "Low", "Volume"]
trainStart = '11-01-2015'       # Start of training period
trainEnd   = '11-01-2017'       # End of training period
testStart  = '11-02-2017'       # Start of testing period
testEnd    = '11-17-2017'       # End of testing period
```

So here is the data from the csv file before i read it.

```
1 Date,Open,High,Low,Close,Volume
2 2015-01-02,5.05,5.18,4.83,5.14,1542452.0
3 2015-01-05,5.15,5.23,4.8,4.99,1207386.0
4 2015-01-06,4.89,4.97,4.75,4.92,704102.0
5 2015-01-07,4.82,4.93,4.75,4.8,614919.0
```
 

```
data = read_csv("file.csv")                                                                                                                                      
data = data.round(3)                    # Round all values                                                                                                               
data['Date'] = to_datetime(data.Date)   #convert Date coloum data to datetime                                                                                            
data['Date'] = data['Date'].dt.strftime('%m-%d-%Y') #convert format of dates
```

output of print(data)

```
0    01-02-2015  5.05  5.18  4.83   5.14   1542452.0
1    01-05-2015  5.15  5.23  4.80   4.99   1207386.0
2    01-06-2015  4.89  4.97  4.75   4.92    704102.0
3    01-07-2015  4.82  4.93  4.75   4.80    614919.0
4    01-08-2015  4.85  4.98  4.65   4.72    686451.0

```

```
Traceback (most recent call last):
File "clair2.py", line 35, in <module>
    backtest.start(data, kernel='rbf', C=1, gamma=10)
  File "/home/kodi/.local/lib/python3.5/site-packages/clairvoyant/engine.py", line 197, in start
    Engine.start(self, data, **kwargs)
  File "/home/kodi/.local/lib/python3.5/site-packages/clairvoyant/engine.py", line 50, in start
    for i in range(self.trainStr, self.trainEnd+1):
TypeError: Can't convert 'int' object to str implicitly
```

```
backtest.start(data, kernel='rbf', C=1, gamma=10)                                                                                                                       
backtest.conditions()                                                                                                                                                   
backtest.statistics()                                                                                                                                                   
backtest.visualize('thin.ol')
```

**Comment by anfederico** [comment]
Getting your data ready is actually separate from the module. You can do it however you want. All you need to do is make sure your data column in your pandas dataframe is converted to datetime.

Look at your CSV file, you want to do something like this

```
data = read_csv("file.csv")                                                                                                                                      
data = data.round(3)                    # Round all values                                                                                                               
data['Date'] = to_datetime(data.Date)   #convert Date coloum data to datetime                                                                                            
data['Date'] = data['Date'].dt.strftime('%Y-%m-%d') #convert format of dates

# 2015-01-02 = %Y-%m-%d
```

Also, what are the features you're using?

**Comment by oppsig** [comment]
Thanks a lot, tried this but still caught same error. Gonna play around to see if i can mange to get it it work but if you want to take a look, then here is my entire script.

https://pastebin.com/KWVGETZg

When i convert the 'Date' column data with 'to_datetime' does it get converted to some sort of object?
The conversion works fine but i guess backtest.start is having problems looping threw the dates (trainStart, trainEnd ect) for some reason.
Can datetime have different formats, like the one your telling me to convert to '%Y-%m-%d

I also changed this to use the same format. Will i need to convert this also to datetime or does your module do this?

```
trainStart = '2015-11-01'       # Start of training period
trainEnd   = '2017-11-01'       # End of training period
testStart  = '2017-11-02'       # Start of testing period
testEnd   = '2017-11-17'       # End of testing period
```

Here's the error.
```
Traceback (most recent call last):
  File "clair2.py", line 36, in <module>
    backtest.start(data, kernel='rbf', C=1, gamma=10)
  File "/home/kodi/.local/lib/python3.5/site-packages/clairvoyant/engine.py", line 197, in start
    Engine.start(self, data, **kwargs)
  File "/home/kodi/.local/lib/python3.5/site-packages/clairvoyant/engine.py", line 50, in start
    for i in range(self.trainStr, self.trainEnd+1):
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by anfederico** [comment]
Closing this, use a numerical index on your dataframe if you're still having issues.
